name: PurePerms
main: PurePerms\Main
version: 1.5.1
api: 5.0.0
author: 64FF00
description: Permissions plugin for PocketMine-MP
commands:
  setgroup:
    description: Set a player's group
    usage: "/setgroup <player> <group>"
  addgroup:
    description: Add a new group
    usage: "/addgroup <group>"
  ppinfo:
    description: View player permission info
    usage: "/ppinfo <player>"
  removegroup:
    description: Remove a group
    usage: "/removegroup <group>"
  listgroups:
    description: List all groups
    usage: "/listgroups"
  addperm:
    description: Add a permission to a group
    usage: "/addperm <group> <permission>"
  removeperm:
    description: Remove a permission from a group
    usage: "/removeperm <group> <permission>"
