name: OVOPerms
main: PurePerms\Main
version: 1.0.0
api: [5.0.0]
author: YourName
description: Permissions plugin for PocketMine-MP
website: https://github.com/YourUsername/YourRepoName

commands:
  setgroup:
    description: Set a player's group
    usage: "/setgroup <player> <group>"
  addgroup:
    description: Add a new group
    usage: "/addgroup <group>"
  removegroup:
    description: Remove a group
    usage: "/removegroup <group>"
  listgroups:
    description: List all groups
    usage: "/listgroups"
  groupinfo:
    description: View group info
    usage: "/groupinfo <group>"
  ppinfo:
    description: View player permission info
    usage: "/ppinfo <player>"
  setperm:
    description: Set a permission for a group
    usage: "/setperm <group> <permission>"
  unsetperm:
    description: Remove a permission from a group
    usage: "/unsetperm <group> <permission>"
